export const dummyPosts = [
    {
        postName: 'Post 1',
        postSubtitle: 'Post 1 subtitle',
        postSmallDescription: 'Commodo labore sunt dolore pariatur quis labore dolor commodo eu voluptate aliqua. Eiusmod culpa incididunt nisi non fugiat ipsum aute. Lorem ullamco ea magna irure ex culpa veniam deserunt ex. Tempor eu officia reprehenderit quis est culpa sunt tempor deserunt sunt ex anim irure ad.Non ea Lorem consequat voluptate aliqua ea ut veniam. Elit.',
        post: 'Exercitation ut laborum exercitation excepteur ut amet ullamco quis consectetur aliqua ex elit. Cupidatat mollit excepteur anim ipsum ut eiusmod ea minim ex. Eu commodo sint esse elit cillum pariatur proident pariatur magna excepteur id. Magna commodo cillum veniam minim labore in. Nostrud consequat aliquip aliqua eu non. Occaecat qui fugiat nostrud in labore officia. Cillum dolore irure fugiat consectetur sunt id commodo aliqua ea fugiat.Ipsum reprehenderit nisi ullamco enim ea id voluptate. Qui mollit fugiat occaecat dolor sunt dolor velit irure non non. Aliqua nulla magna ullamco aute.Mollit dolor ex consectetur reprehenderit est minim ullamco anim anim cupidatat commodo sunt eu. Consequat officia consequat irure eiusmod adipisicing aute proident nulla voluptate ad velit. Consequat qui proident enim nulla exercitation fugiat exercitation irure. Occaecat ullamco anim deserunt laborum. Ullamco cillum tempor magna do elit veniam veniam deserunt consectetur eu voluptate laboris adipisicing consequat. Eiusmod pariatur voluptate eu ipsum cupidatat eu dolor cillum et ea ad. Nisi ut incididunt excepteur culpa laboris nostrud sit aute laboris voluptate.'
    },
    {
        postName: 'Post 1',
        postSubtitle: 'Post 1 subtitle',
        postSmallDescription: 'Commodo labore sunt dolore pariatur quis labore dolor commodo eu voluptate aliqua. Eiusmod culpa incididunt nisi non fugiat ipsum aute. Lorem ullamco ea magna irure ex culpa veniam deserunt ex. Tempor eu officia reprehenderit quis est culpa sunt tempor deserunt sunt ex anim irure ad.Non ea Lorem consequat voluptate aliqua ea ut veniam. Elit.',
        post: 'Exercitation ut laborum exercitation excepteur ut amet ullamco quis consectetur aliqua ex elit. Cupidatat mollit excepteur anim ipsum ut eiusmod ea minim ex. Eu commodo sint esse elit cillum pariatur proident pariatur magna excepteur id. Magna commodo cillum veniam minim labore in. Nostrud consequat aliquip aliqua eu non. Occaecat qui fugiat nostrud in labore officia. Cillum dolore irure fugiat consectetur sunt id commodo aliqua ea fugiat.Ipsum reprehenderit nisi ullamco enim ea id voluptate. Qui mollit fugiat occaecat dolor sunt dolor velit irure non non. Aliqua nulla magna ullamco aute.Mollit dolor ex consectetur reprehenderit est minim ullamco anim anim cupidatat commodo sunt eu. Consequat officia consequat irure eiusmod adipisicing aute proident nulla voluptate ad velit. Consequat qui proident enim nulla exercitation fugiat exercitation irure. Occaecat ullamco anim deserunt laborum. Ullamco cillum tempor magna do elit veniam veniam deserunt consectetur eu voluptate laboris adipisicing consequat. Eiusmod pariatur voluptate eu ipsum cupidatat eu dolor cillum et ea ad. Nisi ut incididunt excepteur culpa laboris nostrud sit aute laboris voluptate.'
    },
    {
        postName: 'Post 1',
        postSubtitle: 'Post 1 subtitle',
        postSmallDescription: 'Commodo labore sunt dolore pariatur quis labore dolor commodo eu voluptate aliqua. Eiusmod culpa incididunt nisi non fugiat ipsum aute. Lorem ullamco ea magna irure ex culpa veniam deserunt ex. Tempor eu officia reprehenderit quis est culpa sunt tempor deserunt sunt ex anim irure ad.Non ea Lorem consequat voluptate aliqua ea ut veniam. Elit.',
        post: 'Exercitation ut laborum exercitation excepteur ut amet ullamco quis consectetur aliqua ex elit. Cupidatat mollit excepteur anim ipsum ut eiusmod ea minim ex. Eu commodo sint esse elit cillum pariatur proident pariatur magna excepteur id. Magna commodo cillum veniam minim labore in. Nostrud consequat aliquip aliqua eu non. Occaecat qui fugiat nostrud in labore officia. Cillum dolore irure fugiat consectetur sunt id commodo aliqua ea fugiat.Ipsum reprehenderit nisi ullamco enim ea id voluptate. Qui mollit fugiat occaecat dolor sunt dolor velit irure non non. Aliqua nulla magna ullamco aute.Mollit dolor ex consectetur reprehenderit est minim ullamco anim anim cupidatat commodo sunt eu. Consequat officia consequat irure eiusmod adipisicing aute proident nulla voluptate ad velit. Consequat qui proident enim nulla exercitation fugiat exercitation irure. Occaecat ullamco anim deserunt laborum. Ullamco cillum tempor magna do elit veniam veniam deserunt consectetur eu voluptate laboris adipisicing consequat. Eiusmod pariatur voluptate eu ipsum cupidatat eu dolor cillum et ea ad. Nisi ut incididunt excepteur culpa laboris nostrud sit aute laboris voluptate.'
    },
    {
        postName: 'Post 1',
        postSubtitle: 'Post 1 subtitle',
        postSmallDescription: 'Commodo labore sunt dolore pariatur quis labore dolor commodo eu voluptate aliqua. Eiusmod culpa incididunt nisi non fugiat ipsum aute. Lorem ullamco ea magna irure ex culpa veniam deserunt ex. Tempor eu officia reprehenderit quis est culpa sunt tempor deserunt sunt ex anim irure ad.Non ea Lorem consequat voluptate aliqua ea ut veniam. Elit.',
        post: 'Exercitation ut laborum exercitation excepteur ut amet ullamco quis consectetur aliqua ex elit. Cupidatat mollit excepteur anim ipsum ut eiusmod ea minim ex. Eu commodo sint esse elit cillum pariatur proident pariatur magna excepteur id. Magna commodo cillum veniam minim labore in. Nostrud consequat aliquip aliqua eu non. Occaecat qui fugiat nostrud in labore officia. Cillum dolore irure fugiat consectetur sunt id commodo aliqua ea fugiat.Ipsum reprehenderit nisi ullamco enim ea id voluptate. Qui mollit fugiat occaecat dolor sunt dolor velit irure non non. Aliqua nulla magna ullamco aute.Mollit dolor ex consectetur reprehenderit est minim ullamco anim anim cupidatat commodo sunt eu. Consequat officia consequat irure eiusmod adipisicing aute proident nulla voluptate ad velit. Consequat qui proident enim nulla exercitation fugiat exercitation irure. Occaecat ullamco anim deserunt laborum. Ullamco cillum tempor magna do elit veniam veniam deserunt consectetur eu voluptate laboris adipisicing consequat. Eiusmod pariatur voluptate eu ipsum cupidatat eu dolor cillum et ea ad. Nisi ut incididunt excepteur culpa laboris nostrud sit aute laboris voluptate.'
    },
    {
        postName: 'Post 1',
        postSubtitle: 'Post 1 subtitle',
        postSmallDescription: 'Commodo labore sunt dolore pariatur quis labore dolor commodo eu voluptate aliqua. Eiusmod culpa incididunt nisi non fugiat ipsum aute. Lorem ullamco ea magna irure ex culpa veniam deserunt ex. Tempor eu officia reprehenderit quis est culpa sunt tempor deserunt sunt ex anim irure ad.Non ea Lorem consequat voluptate aliqua ea ut veniam. Elit.',
        post: 'Exercitation ut laborum exercitation excepteur ut amet ullamco quis consectetur aliqua ex elit. Cupidatat mollit excepteur anim ipsum ut eiusmod ea minim ex. Eu commodo sint esse elit cillum pariatur proident pariatur magna excepteur id. Magna commodo cillum veniam minim labore in. Nostrud consequat aliquip aliqua eu non. Occaecat qui fugiat nostrud in labore officia. Cillum dolore irure fugiat consectetur sunt id commodo aliqua ea fugiat.Ipsum reprehenderit nisi ullamco enim ea id voluptate. Qui mollit fugiat occaecat dolor sunt dolor velit irure non non. Aliqua nulla magna ullamco aute.Mollit dolor ex consectetur reprehenderit est minim ullamco anim anim cupidatat commodo sunt eu. Consequat officia consequat irure eiusmod adipisicing aute proident nulla voluptate ad velit. Consequat qui proident enim nulla exercitation fugiat exercitation irure. Occaecat ullamco anim deserunt laborum. Ullamco cillum tempor magna do elit veniam veniam deserunt consectetur eu voluptate laboris adipisicing consequat. Eiusmod pariatur voluptate eu ipsum cupidatat eu dolor cillum et ea ad. Nisi ut incididunt excepteur culpa laboris nostrud sit aute laboris voluptate.'
    },
    {
        postName: 'Post 1',
        postSubtitle: 'Post 1 subtitle',
        postSmallDescription: 'Commodo labore sunt dolore pariatur quis labore dolor commodo eu voluptate aliqua. Eiusmod culpa incididunt nisi non fugiat ipsum aute. Lorem ullamco ea magna irure ex culpa veniam deserunt ex. Tempor eu officia reprehenderit quis est culpa sunt tempor deserunt sunt ex anim irure ad.Non ea Lorem consequat voluptate aliqua ea ut veniam. Elit.',
        post: 'Exercitation ut laborum exercitation excepteur ut amet ullamco quis consectetur aliqua ex elit. Cupidatat mollit excepteur anim ipsum ut eiusmod ea minim ex. Eu commodo sint esse elit cillum pariatur proident pariatur magna excepteur id. Magna commodo cillum veniam minim labore in. Nostrud consequat aliquip aliqua eu non. Occaecat qui fugiat nostrud in labore officia. Cillum dolore irure fugiat consectetur sunt id commodo aliqua ea fugiat.Ipsum reprehenderit nisi ullamco enim ea id voluptate. Qui mollit fugiat occaecat dolor sunt dolor velit irure non non. Aliqua nulla magna ullamco aute.Mollit dolor ex consectetur reprehenderit est minim ullamco anim anim cupidatat commodo sunt eu. Consequat officia consequat irure eiusmod adipisicing aute proident nulla voluptate ad velit. Consequat qui proident enim nulla exercitation fugiat exercitation irure. Occaecat ullamco anim deserunt laborum. Ullamco cillum tempor magna do elit veniam veniam deserunt consectetur eu voluptate laboris adipisicing consequat. Eiusmod pariatur voluptate eu ipsum cupidatat eu dolor cillum et ea ad. Nisi ut incididunt excepteur culpa laboris nostrud sit aute laboris voluptate.'
    },
    {
        postName: 'Post 1',
        postSubtitle: 'Post 1 subtitle',
        postSmallDescription: 'Commodo labore sunt dolore pariatur quis labore dolor commodo eu voluptate aliqua. Eiusmod culpa incididunt nisi non fugiat ipsum aute. Lorem ullamco ea magna irure ex culpa veniam deserunt ex. Tempor eu officia reprehenderit quis est culpa sunt tempor deserunt sunt ex anim irure ad.Non ea Lorem consequat voluptate aliqua ea ut veniam. Elit.',
        post: 'Exercitation ut laborum exercitation excepteur ut amet ullamco quis consectetur aliqua ex elit. Cupidatat mollit excepteur anim ipsum ut eiusmod ea minim ex. Eu commodo sint esse elit cillum pariatur proident pariatur magna excepteur id. Magna commodo cillum veniam minim labore in. Nostrud consequat aliquip aliqua eu non. Occaecat qui fugiat nostrud in labore officia. Cillum dolore irure fugiat consectetur sunt id commodo aliqua ea fugiat.Ipsum reprehenderit nisi ullamco enim ea id voluptate. Qui mollit fugiat occaecat dolor sunt dolor velit irure non non. Aliqua nulla magna ullamco aute.Mollit dolor ex consectetur reprehenderit est minim ullamco anim anim cupidatat commodo sunt eu. Consequat officia consequat irure eiusmod adipisicing aute proident nulla voluptate ad velit. Consequat qui proident enim nulla exercitation fugiat exercitation irure. Occaecat ullamco anim deserunt laborum. Ullamco cillum tempor magna do elit veniam veniam deserunt consectetur eu voluptate laboris adipisicing consequat. Eiusmod pariatur voluptate eu ipsum cupidatat eu dolor cillum et ea ad. Nisi ut incididunt excepteur culpa laboris nostrud sit aute laboris voluptate.'
    },
    {
        postName: 'Post 1',
        postSubtitle: 'Post 1 subtitle',
        postSmallDescription: 'Commodo labore sunt dolore pariatur quis labore dolor commodo eu voluptate aliqua. Eiusmod culpa incididunt nisi non fugiat ipsum aute. Lorem ullamco ea magna irure ex culpa veniam deserunt ex. Tempor eu officia reprehenderit quis est culpa sunt tempor deserunt sunt ex anim irure ad.Non ea Lorem consequat voluptate aliqua ea ut veniam. Elit.',
        post: 'Exercitation ut laborum exercitation excepteur ut amet ullamco quis consectetur aliqua ex elit. Cupidatat mollit excepteur anim ipsum ut eiusmod ea minim ex. Eu commodo sint esse elit cillum pariatur proident pariatur magna excepteur id. Magna commodo cillum veniam minim labore in. Nostrud consequat aliquip aliqua eu non. Occaecat qui fugiat nostrud in labore officia. Cillum dolore irure fugiat consectetur sunt id commodo aliqua ea fugiat.Ipsum reprehenderit nisi ullamco enim ea id voluptate. Qui mollit fugiat occaecat dolor sunt dolor velit irure non non. Aliqua nulla magna ullamco aute.Mollit dolor ex consectetur reprehenderit est minim ullamco anim anim cupidatat commodo sunt eu. Consequat officia consequat irure eiusmod adipisicing aute proident nulla voluptate ad velit. Consequat qui proident enim nulla exercitation fugiat exercitation irure. Occaecat ullamco anim deserunt laborum. Ullamco cillum tempor magna do elit veniam veniam deserunt consectetur eu voluptate laboris adipisicing consequat. Eiusmod pariatur voluptate eu ipsum cupidatat eu dolor cillum et ea ad. Nisi ut incididunt excepteur culpa laboris nostrud sit aute laboris voluptate.'
    },
    {
        postName: 'Post 1',
        postSubtitle: 'Post 1 subtitle',
        postSmallDescription: 'Commodo labore sunt dolore pariatur quis labore dolor commodo eu voluptate aliqua. Eiusmod culpa incididunt nisi non fugiat ipsum aute. Lorem ullamco ea magna irure ex culpa veniam deserunt ex. Tempor eu officia reprehenderit quis est culpa sunt tempor deserunt sunt ex anim irure ad.Non ea Lorem consequat voluptate aliqua ea ut veniam. Elit.',
        post: 'Exercitation ut laborum exercitation excepteur ut amet ullamco quis consectetur aliqua ex elit. Cupidatat mollit excepteur anim ipsum ut eiusmod ea minim ex. Eu commodo sint esse elit cillum pariatur proident pariatur magna excepteur id. Magna commodo cillum veniam minim labore in. Nostrud consequat aliquip aliqua eu non. Occaecat qui fugiat nostrud in labore officia. Cillum dolore irure fugiat consectetur sunt id commodo aliqua ea fugiat.Ipsum reprehenderit nisi ullamco enim ea id voluptate. Qui mollit fugiat occaecat dolor sunt dolor velit irure non non. Aliqua nulla magna ullamco aute.Mollit dolor ex consectetur reprehenderit est minim ullamco anim anim cupidatat commodo sunt eu. Consequat officia consequat irure eiusmod adipisicing aute proident nulla voluptate ad velit. Consequat qui proident enim nulla exercitation fugiat exercitation irure. Occaecat ullamco anim deserunt laborum. Ullamco cillum tempor magna do elit veniam veniam deserunt consectetur eu voluptate laboris adipisicing consequat. Eiusmod pariatur voluptate eu ipsum cupidatat eu dolor cillum et ea ad. Nisi ut incididunt excepteur culpa laboris nostrud sit aute laboris voluptate.'
    }
]